# Generated by Django 4.2.1 on 2023-08-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_category_alter_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
