# Generated by Django 4.2.1 on 2023-08-15 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='contact_number',
            new_name='phone_no',
        ),
    ]
